services:

  nginx-proxy:
    container_name: nginx-proxy
    image: nginxproxy/nginx-proxy:1.6.1-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - reverse-proxy
    volumes:
      - ./redirect.conf:/etc/nginx/conf.d/redirect.conf:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d  # configuration of vhosts

  acme-companion:
    image: nginxproxy/acme-companion
    environment:
      DEFAULT_EMAIL: __LETSENCRYPT_EMAIL__
      ACME_CA_URI: https://acme-v02.api.letsencrypt.org/directory
      NGINX_PROXY_CONTAINER: nginx-proxy
    networks:
      - reverse-proxy
    volumes:
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html  # writes http-01 challenge files
      - vhost:/etc/nginx/vhost.d
    depends_on:
      - nginx-proxy

volumes:
  certs:
  html:
  vhost:
  acme:

networks:
  reverse-proxy:
