# Generated by Django 5.1.1 on 2024-12-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="has_email_notifications_enabled",
            field=models.BooleanField(default=True, verbose_name="Email notifications enabled"),
        ),
    ]
