# Generated by Django 5.1.1 on 2024-10-12 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0002_alter_club_options"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newagentrequest",
            name="club",
            field=models.ForeignKey(
                blank=True,
                help_text="The club the agent has permission to manage",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="clubs.club",
            ),
        ),
    ]
