# Generated by Django 5.1.7 on 2025-03-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_agent_has_email_notifications_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="picture_url",
            field=models.URLField(blank=True),
        ),
    ]
