# Generated by Django 5.1.7 on 2025-03-28 22:48

import core.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_agent_picture_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newagentrequest",
            name="email",
            field=core.fields.ValidatedEmailField(
                max_length=254, unique=True, validators=[core.fields.validate_email_domain_typos]
            ),
        ),
    ]
