# Generated by Django 5.1.7 on 2025-03-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_newagentrequest_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="has_guest_players_notifications_enabled",
            field=models.BooleanField(
                default=True, verbose_name="Guest players notifications enabled"
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="has_roster_reminders_enabled",
            field=models.BooleanField(default=True, verbose_name="Roster reminders enabled"),
        ),
        migrations.AlterField(
            model_name="agent",
            name="has_email_notifications_enabled",
            field=models.BooleanField(
                default=True,
                help_text="If disabled, no emails will be sent",
                verbose_name="Email notifications enabled",
            ),
        ),
    ]
