# Generated by Django 5.2.6 on 2025-10-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "email_required",
                    models.BooleanField(
                        default=False,
                        help_text=(
                            "Require email for members 15+ years"
                            " and legal guardian email for children under 15"
                        ),
                    ),
                ),
                (
                    "email_verification_required",
                    models.BooleanField(
                        default=False,
                        help_text=(
                            "Block adding members to tournament rosters if email is not verified"
                        ),
                    ),
                ),
                (
                    "min_age_verification_required",
                    models.BooleanField(
                        default=False,
                        help_text=(
                            "Enforce minimum age validation for"
                            " tournaments (when disabled, only max age is checked)"
                        ),
                    ),
                ),
                (
                    "team_management_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Show/hide team management UI in club administration",
                    ),
                ),
                (
                    "transfers_enabled",
                    models.BooleanField(
                        default=False, help_text="Show/hide player transfer UI between clubs"
                    ),
                ),
            ],
            options={
                "verbose_name": "Application Settings",
            },
        ),
    ]
