# Generated by Django 6.1 on 2026-08-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_unaccent_extension"),
    ]

    operations = [
        migrations.AddField(
            model_name="appsettings",
            name="club_logo_upload_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Let clubs upload their own logo; when off, only admins can set it",
            ),
        ),
    ]
