services:
  app:
    container_name: app
    image: ultihub
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    restart: always
    entrypoint: ["/app/ultihub/manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ../ultihub/:/app/ultihub
      - ../static/:/app/ultihub/static
    environment:
      PYTHONUNBUFFERED: true
    env_file:
      - ../secrets/.env.dev

  worker:
    image: ultihub
    restart: always
    entrypoint: ["/app/ultihub/manage.py", "run_huey", "-q"]
    volumes:
      - ../ultihub/:/app/ultihub
    depends_on:
      - redis
    env_file:
      - ../secrets/.env.dev
    environment:
      PYTHONUNBUFFERED: true

  redis:
    image: redis:alpine
    restart: always
    expose:
      - 6379

  db:
    image: postgres:16.4-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ultihub
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ultihub

volumes:
  postgres_data:
