# Generated by Django 5.1.1 on 2024-11-12 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0001_initial"),
        ("competitions", "0002_alter_competition_unique_together_and_more"),
        ("finance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="competitionapplication",
            name="invoice",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applications",
                to="finance.invoice",
            ),
        ),
        migrations.AddField(
            model_name="competitionapplication",
            name="registered_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="competitionapplication",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="competition_application",
                to="clubs.team",
            ),
        ),
        migrations.RemoveField(
            model_name="competition",
            name="is_on_beach",
        ),
        migrations.AlterUniqueTogether(
            name="competitionapplication",
            unique_together={("competition", "team")},
        ),
    ]
