# Generated by Django 5.1.1 on 2024-11-13 12:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0003_competitionapplication_invoice_and_more"),
    ]

    operations = []
