# Generated by Django 5.1.1 on 2024-11-13 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0004_tournament_teamattournament"),
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competitionapplication",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applications",
                to="finance.invoice",
            ),
        ),
    ]
