# Generated by Django 5.1.1 on 2024-12-11 23:00
import django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0006_season_invoices_generated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.RenameField(
            model_name="season",
            old_name="player_fee",
            new_name="discounted_fee",
        ),
        migrations.AddField(
            model_name="season",
            name="fee_at_tournament",
            field=models.DecimalField(
                decimal_places=2,
                default="0.00",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="season",
            name="regular_fee",
            field=models.DecimalField(
                decimal_places=2,
                default="0.00",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="competition",
            name="player_fee_per_tournament",
        ),
        migrations.AddField(
            model_name="competition",
            name="fee_type",
            field=models.IntegerField(
                choices=[(1, "Free"), (2, "Discounted"), (3, "Regular")], default=1
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="competition",
            name="is_exempted_from_season_fee",
        ),
        migrations.AlterField(
            model_name="competition",
            name="fee_type",
            field=models.IntegerField(
                choices=[(1, "Free"), (2, "Discounted"), (3, "Regular")],
                help_text="FREE and DISCOUNTED cause no player fee to be charged",
            ),
        ),
    ]
