# Generated by Django 5.1.1 on 2024-12-23 21:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0007_competition_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="competitionapplication",
            name="final_placement",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
