# Generated by Django 5.1.4 on 2024-12-28 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0009_club_short_name"),
        ("competitions", "0009_agelimit_season_age_reference_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competitionapplication",
            name="competition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applications",
                to="competitions.competition",
            ),
        ),
        migrations.AlterField(
            model_name="competitionapplication",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applications",
                to="clubs.team",
            ),
        ),
    ]
