# Generated by Django 5.1.6 on 2025-03-08 09:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0011_alter_competitionapplication_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agelimit",
            name="m_max",
            field=models.PositiveSmallIntegerField(
                default=99,
                help_text="Maximum age allowed (inclusive) for men",
                validators=[django.core.validators.MaxValueValidator(99)],
                verbose_name="Maximum age for men",
            ),
        ),
    ]
