# Generated by Django 5.2.6 on 2025-10-16 19:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0012_alter_agelimit_m_max"),
    ]

    operations = [
        migrations.RenameField(
            model_name="competition",
            old_name="type",
            new_name="environment",
        ),
        migrations.RemoveField(
            model_name="competition",
            name="is_for_national_teams",
        ),
    ]
