# Generated by Django 5.2.11 on 2026-04-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0013_rename_type_to_environment"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="allow_team_transfers",
            field=models.BooleanField(
                default=False,
                help_text="Allow a player to transfer between teams within this competition",
            ),
        ),
    ]
