# Generated by Django 5.1.4 on 2024-12-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="memberattournament",
            name="is_spirit_captain",
            field=models.BooleanField(
                default=False,
                help_text="Only one spirit captain per team is allowed",
                verbose_name="Spirit captain",
            ),
        ),
        migrations.AlterField(
            model_name="memberattournament",
            name="is_captain",
            field=models.BooleanField(
                default=False,
                help_text="Only one captain per team is allowed",
                verbose_name="Captain",
            ),
        ),
    ]
