# Generated by Django 5.1.4 on 2024-12-28 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0010_alter_competitionapplication_competition_and_more"),
        ("tournaments", "0002_memberattournament_is_spirit_captain_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberattournament",
            name="team_at_tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="members",
                to="tournaments.teamattournament",
            ),
        ),
        migrations.AlterField(
            model_name="memberattournament",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="members",
                to="tournaments.tournament",
            ),
        ),
        migrations.AlterField(
            model_name="teamattournament",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="teams",
                to="tournaments.tournament",
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="competition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tournaments",
                to="competitions.competition",
            ),
        ),
    ]
