# Generated by Django 5.1.4 on 2025-01-23 19:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0011_alter_competitionapplication_state"),
        ("tournaments", "0003_alter_memberattournament_team_at_tournament_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="teamattournament",
            unique_together={("tournament", "application")},
        ),
        migrations.AddField(
            model_name="teamattournament",
            name="seeding",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterUniqueTogether(
            name="teamattournament",
            unique_together={("tournament", "application"), ("tournament", "seeding")},
        ),
    ]
