# Generated by Django 5.1.4

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0004_alter_teamattournament_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="winner_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="won_tournaments",
                to="tournaments.teamattournament",
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="sotg_winner_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sotg_won_tournaments",
                to="tournaments.teamattournament",
            ),
        ),
    ]
