# Generated by Django 5.1.7 on 2025-03-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0004_alter_teamattournament_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="are_reminders_sent",
            field=models.BooleanField(default=False),
        ),
    ]
