# Generated by Django 5.1.4

from typing import Any

from django.db import migrations


def populate_tournament_winners(apps: Any, schema_editor: Any) -> None:
    """Populate winner_team and sotg_winner_team for existing tournaments."""
    Tournament = apps.get_model("tournaments", "Tournament")
    TeamAtTournament = apps.get_model("tournaments", "TeamAtTournament")

    for tournament in Tournament.objects.all():
        # Get winner team (final_placement=1)
        tournament.winner_team = TeamAtTournament.objects.filter(
            tournament=tournament, final_placement=1
        ).first()
        tournament.sotg_winner_team = (
            TeamAtTournament.objects.filter(tournament=tournament)
            .exclude(spirit_avg__isnull=True)
            .order_by("-spirit_avg", "final_placement")
            .first()
        )

        tournament.save(update_fields=["winner_team", "sotg_winner_team"])


def reverse_populate_tournament_winners(apps: Any, schema_editor: Any) -> None:
    """Clear winner_team and sotg_winner_team fields."""
    Tournament = apps.get_model("tournaments", "Tournament")
    Tournament.objects.all().update(winner_team=None, sotg_winner_team=None)


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0005_tournament_winner_team_sotg_winner_team"),
    ]

    operations = [
        migrations.RunPython(populate_tournament_winners, reverse_populate_tournament_winners),
    ]
