# Generated by Django 5.1.1 on 2024-11-28 21:24

import django.core.validators
import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models

import members.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clubs", "0007_remove_member_club_delete_coachlicence_delete_member"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Member",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        ("first_name", models.CharField(max_length=32)),
                        ("last_name", models.CharField(max_length=32)),
                        ("birth_date", models.DateField()),
                        ("sex", models.IntegerField(choices=[(1, "Female"), (2, "Male")])),
                        (
                            "citizenship",
                            django_countries.fields.CountryField(default="CZ", max_length=2),
                        ),
                        (
                            "birth_number",
                            models.CharField(
                                blank=True,
                                help_text="Required for czech citizens",
                                max_length=10,
                                validators=[members.validators.validate_czech_birth_number],
                            ),
                        ),
                        (
                            "address",
                            models.CharField(
                                blank=True,
                                help_text="Required for non-czech citizens",
                                max_length=128,
                            ),
                        ),
                        (
                            "email",
                            models.EmailField(
                                blank=True,
                                help_text="Member has to confirm this email",
                                max_length=254,
                            ),
                        ),
                        ("email_confirmation_token", models.UUIDField(editable=False, null=True)),
                        ("has_email_confirmed", models.BooleanField(default=False)),
                        ("marketing_consent_given_at", models.DateTimeField(null=True)),
                        (
                            "is_active",
                            models.BooleanField(
                                default=True,
                                help_text=(
                                    "If you no longer need the member, you can deactivate them."
                                    " This means they will not appear in selection lists for"
                                    " rosters, etc. You can reactivate the member at any time."
                                ),
                            ),
                        ),
                        ("is_favourite", models.BooleanField(default=False)),
                        (
                            "default_jersey_number",
                            models.IntegerField(
                                blank=True,
                                null=True,
                                validators=[
                                    django.core.validators.MinValueValidator(1),
                                    django.core.validators.MaxValueValidator(99),
                                ],
                            ),
                        ),
                        (
                            "club",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.PROTECT, to="clubs.club"
                            ),
                        ),
                    ],
                    options={
                        "db_table": "clubs_member",
                    },
                ),
                migrations.CreateModel(
                    name="CoachLicence",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        (
                            "level",
                            models.IntegerField(
                                choices=[(1, "First"), (2, "Second"), (3, "Third")]
                            ),
                        ),
                        ("valid_from", models.DateField()),
                        ("valid_to", models.DateField()),
                        (
                            "member",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.PROTECT, to="members.member"
                            ),
                        ),
                    ],
                    options={
                        "db_table": "clubs_coachlicence",
                    },
                ),
            ]
        )
    ]
