# Generated by Django 5.1.1 on 2024-11-28 21:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="coachlicence",
            table=None,
        ),
        migrations.AlterModelTable(
            name="member",
            table=None,
        ),
    ]
