# Generated by Django 5.1.1 on 2024-12-11 16:43

from django.db import migrations, models

import members.validators


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0003_transfer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="address",
        ),
        migrations.AddField(
            model_name="member",
            name="city",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="member",
            name="house_number",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="member",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=5, validators=[members.validators.validate_postal_code]
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="street",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
