# Generated by Django 5.1.4 on 2024-12-27 15:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0004_remove_member_address_member_city_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="is_favourite",
        ),
    ]
