# Generated by Django 5.1.4 on 2025-02-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0012_alter_team_options"),
        ("members", "0005_remove_member_is_favourite"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="original_id",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddConstraint(
            model_name="member",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("original_id__isnull", False), models.Q(("original_id", ""), _negated=True)
                ),
                fields=("original_id",),
                name="unique_original_id_non_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="member",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("birth_number__isnull", False), models.Q(("birth_number", ""), _negated=True)
                ),
                fields=("birth_number",),
                name="unique_birth_number_non_null",
            ),
        ),
    ]
