# Generated by Django 5.1.4 on 2025-02-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0006_member_original_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="marketing_consent_given_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
