# Generated by Django 5.1.6 on 2025-02-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0007_alter_member_marketing_consent_given_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="has_email_confirmed",
        ),
        migrations.AddField(
            model_name="member",
            name="email_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="legal_guardian_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="member",
            name="legal_guardian_first_name",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="member",
            name="legal_guardian_last_name",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="member",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
