# Generated by Django 5.1.4 on 2024-12-27 09:51

from django.db import migrations
from django.db.models import F


def forwards_func(apps, schema_editor):  # type: ignore
    Member = apps.get_model("members", "Member")

    Member.objects.filter(marketing_consent_given_at__isnull=False).update(
        email_confirmed_at=F("marketing_consent_given_at")
    )


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0008_remove_member_has_email_confirmed_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_code=migrations.RunPython.noop),
    ]
