# Generated by Django 5.1.7 on 2025-03-28 22:48

import core.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0009_fix_email_confirmation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="email",
            field=core.fields.ValidatedEmailField(
                blank=True, max_length=254, validators=[core.fields.validate_email_domain_typos]
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="legal_guardian_email",
            field=core.fields.ValidatedEmailField(
                blank=True, max_length=254, validators=[core.fields.validate_email_domain_typos]
            ),
        ),
    ]
