# Generated by Django 5.2.6 on 2025-11-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0010_alter_member_email_alter_member_legal_guardian_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transfer",
            name="state",
            field=models.IntegerField(
                choices=[
                    (1, "Requested"),
                    (2, "Processed"),
                    (3, "Revoked"),
                    (4, "Rejected"),
                    (5, "Cancelled"),
                ],
                default=1,
            ),
        ),
    ]
