# Generated by Django 5.2.11 on 2026-06-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0015_alter_club_email"),
        ("members", "0012_member_email_confirmation_token_created_at"),
        ("users", "0004_alter_newagentrequest_email"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="transfer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state", 1)),
                fields=("member", "source_club", "target_club"),
                name="unique_requested_transfer_per_member",
            ),
        ),
    ]
