# Generated by Django 6.0.6 on 2026-06-18 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0013_transfer_unique_requested_transfer_per_member"),
        ("users", "0004_alter_newagentrequest_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="FavouriteMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favourite_members",
                        to="users.agent",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favoured_by",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("agent", "member"), name="unique_favourite_member_per_agent"
                    )
                ],
            },
        ),
    ]
