# Generated by Django 5.1.1 on 2024-11-12 15:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clubs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state",
                    models.IntegerField(
                        choices=[
                            (1, "Draft"),
                            (2, "Sent To Fakturoid"),
                            (3, "Paid"),
                            (4, "Cancelled"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[(1, "Competition Deposit"), (2, "Annual Player Fees")]
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="clubs.club"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
