# Generated by Django 5.1.4 on 2024-12-28 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0002_invoicerelatedobject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="type",
            field=models.IntegerField(
                choices=[(1, "Competition Deposit"), (2, "Season Player Fees")]
            ),
        ),
    ]
