# Generated by Django 5.1.4 on 2024-12-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0003_alter_invoice_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="fakturoid_invoice_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="fakturoid_public_html_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="fakturoid_status",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="invoice",
            name="fakturoid_total",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="state",
            field=models.IntegerField(choices=[(1, "Draft"), (2, "Open"), (3, "Paid")], default=1),
        ),
    ]
