# Generated by Django 5.1.6 on 2025-03-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0004_invoice_fakturoid_invoice_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice",
            old_name="amount",
            new_name="original_amount",
        ),
        migrations.AddField(
            model_name="invoice",
            name="lines",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="fakturoid_invoice_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="state",
            field=models.IntegerField(
                choices=[(1, "Draft"), (2, "Open"), (3, "Paid"), (4, "Canceled")], default=1
            ),
        ),
    ]
