# Generated by Django 5.1.6 on 2025-03-15 12:00

import logging
from typing import Any

from django.db import migrations

logger = logging.getLogger(__name__)


def remove_zero_amount_invoices(apps: Any, schema_editor: Any) -> None:
    """
    Remove all invoices with original_amount = 0 and their related objects.
    """
    Invoice = apps.get_model("finance", "Invoice")
    InvoiceRelatedObject = apps.get_model("finance", "InvoiceRelatedObject")
    CompetitionApplication = apps.get_model("competitions", "CompetitionApplication")

    # Find all invoices with zero amount
    zero_amount_invoices = Invoice.objects.filter(original_amount=0)
    zero_invoice_ids = list(zero_amount_invoices.values_list("id", flat=True))

    if zero_invoice_ids:
        # Remove related objects
        InvoiceRelatedObject.objects.filter(invoice_id__in=zero_invoice_ids).delete()

        # Remove invoice references from competition applications
        CompetitionApplication.objects.filter(invoice_id__in=zero_invoice_ids).update(invoice=None)

        # Delete the invoices
        count = zero_amount_invoices.delete()[0]
        logger.info("Removed %s zero-amount invoices and their related objects", count)


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0005_rename_amount_invoice_original_amount_invoice_lines"),
        ("competitions", "0012_alter_agelimit_m_max"),
    ]

    operations = [
        migrations.RunPython(remove_zero_amount_invoices, migrations.RunPython.noop),
    ]
