# Generated by Django 5.1.4 on 2025-01-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0006_remove_zero_amount_invoices"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="fakturoid_due_on",
            field=models.DateField(blank=True, null=True),
        ),
    ]
