# Generated by Django 5.2.11 on 2026-06-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0007_invoice_fakturoid_due_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="state",
            field=models.IntegerField(
                choices=[(1, "Draft"), (2, "Open"), (3, "Paid"), (4, "Canceled")],
                db_index=True,
                default=1,
            ),
        ),
    ]
