# Generated by Django 5.1.1 on 2024-10-30 08:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import clubs.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=48)),
                ("email", models.EmailField(help_text="Contact email of the club", max_length=254)),
                ("website", models.URLField(help_text="URL of the club's website")),
                (
                    "city",
                    models.CharField(help_text="City where the club is located", max_length=64),
                ),
            ],
            options={
                "permissions": (("manage_club", "Can manage club"),),
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=64, unique=True)),
                (
                    "identification_number",
                    models.CharField(
                        help_text="Company identification number",
                        max_length=8,
                        unique=True,
                        validators=[clubs.validators.validate_identification_number],
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        blank=True,
                        max_length=17,
                    ),
                ),
                (
                    "bank_code",
                    models.CharField(blank=True, max_length=4),
                ),
                ("street", models.CharField(max_length=64)),
                ("city", models.CharField(max_length=64)),
                (
                    "postal_code",
                    models.CharField(
                        max_length=6,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Postal code must be in format XXXXX or XXX XX.",
                                regex="^\\d{3}\\s?\\d{2}$",
                            )
                        ],
                    ),
                ),
                ("country", models.CharField(default="Česká republika", max_length=32)),
                (
                    "club",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="clubs.club"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=48)),
                (
                    "description",
                    models.CharField(
                        blank=True, help_text="Only for club internal purposes", max_length=64
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "club",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="clubs.club"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
