# Generated by Django 5.1.1 on 2024-10-06 19:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import clubs.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128, unique=True)),
                (
                    "identification_number",
                    models.CharField(
                        help_text="IČO",
                        max_length=8,
                        unique=True,
                        validators=[clubs.validators.validate_identification_number],
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        max_length=17,
                        unique=True,
                        validators=[clubs.validators.validate_account_number],
                    ),
                ),
                (
                    "bank_code",
                    models.CharField(
                        max_length=4, validators=[clubs.validators.validate_bank_code]
                    ),
                ),
                ("street", models.CharField(max_length=128)),
                ("city", models.CharField(max_length=128)),
                (
                    "postal_code",
                    models.CharField(
                        max_length=6,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Postal code must be in format XXXXX or XXX XX.",
                                regex="^\\d{3}\\s?\\d{2}$",
                            )
                        ],
                    ),
                ),
                ("country", models.CharField(default="Česká republika", max_length=50)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                ("email", models.EmailField(max_length=254)),
                ("website", models.URLField()),
                ("city", models.CharField(max_length=128)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="clubs.organization"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
