# Generated by Django 5.1.1 on 2024-10-12 18:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="club",
            options={"permissions": (("manage_club", "Can manage club"),)},
        ),
    ]
