# Generated by Django 5.1.1 on 2024-11-13 18:56

from django.db import migrations, models

import clubs.validators


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0002_remove_organization_account_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="identification_number",
            field=models.CharField(
                blank=True,
                help_text="Company identification number",
                max_length=8,
                null=True,
                validators=[clubs.validators.validate_identification_number],
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="organization_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the organization with legal entity status",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="city",
            field=models.CharField(
                blank=True, help_text="City where the club is located", max_length=64, null=True
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="email",
            field=models.EmailField(
                blank=True, help_text="Contact email of the club", max_length=254, null=True
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="name",
            field=models.CharField(
                help_text="Only administrators can change this value", max_length=48
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="website",
            field=models.URLField(blank=True, help_text="URL of the club's website", null=True),
        ),
        migrations.DeleteModel(
            name="Organization",
        ),
    ]
