# Generated by Django 5.1.1 on 2024-11-18 22:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0005_member_coachlicence"),
    ]

    operations = [
        migrations.RenameField(
            model_name="member",
            old_name="is_email_confirmed",
            new_name="has_email_confirmed",
        ),
        migrations.AddField(
            model_name="member",
            name="email_confirmation_token",
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
