# Generated by Django 5.1.1 on 2024-11-28 21:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0006_rename_is_email_confirmed_member_has_email_confirmed_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="member",
                    name="club",
                ),
                migrations.DeleteModel(
                    name="CoachLicence",
                ),
                migrations.DeleteModel(
                    name="Member",
                ),
            ]
        )
    ]
