# Generated by Django 5.1.1 on 2024-12-13 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0007_remove_member_club_delete_coachlicence_delete_member"),
        ("users", "0002_agent_has_email_notifications_enabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClubNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("subject", models.CharField(max_length=64)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                (
                    "agent_at_club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="users.agentatclub"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
