# Generated by Django 5.1.4 on 2024-12-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0009_club_short_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="fakturoid_subject_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text=(
                    "ID of the subject in Fakturoid. The club cannot be invoiced without this ID."
                ),
                null=True,
            ),
        ),
    ]
