# Generated by Django 5.1.4 on 2025-02-06 11:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0010_club_fakturoid_subject_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="short_name",
            field=models.CharField(
                blank=True,
                help_text="Short name of the club (2-4 characters)",
                max_length=4,
                validators=[django.core.validators.MinLengthValidator(2)],
            ),
        ),
    ]
