# Generated by Django 5.1.4 on 2025-02-06 16:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0011_alter_club_short_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team",
            options={"ordering": ["name"]},
        ),
    ]
