# Generated by Django 5.1.6 on 2025-03-06 23:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0012_alter_team_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team",
            options={},
        ),
        migrations.AlterField(
            model_name="club",
            name="fakturoid_subject_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text=(
                    "ID of the subject in Fakturoid. The club cannot be invoiced without this ID."
                ),
                null=True,
                unique=True,
            ),
        ),
    ]
