# Generated by Django 5.1.7 on 2025-03-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0013_alter_team_options_alter_club_fakturoid_subject_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="fakturoid_subject_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text=(
                    "ID of the subject in Fakturoid. The club cannot be invoiced without this ID."
                ),
                null=True,
            ),
        ),
    ]
