# Generated by Django 5.1.7 on 2025-03-28 22:48

import core.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0014_alter_club_fakturoid_subject_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="email",
            field=core.fields.ValidatedEmailField(
                blank=True,
                help_text="Contact email of the club",
                max_length=254,
                validators=[core.fields.validate_email_domain_typos],
            ),
        ),
    ]
