# Generated by Django 6.1 on 2026-08-25 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0015_alter_club_email"),
        ("users", "0004_alter_newagentrequest_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="logo_updated_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="Timestamp of the approved logo. Empty means no logo is in use.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ClubLogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("large", models.BinaryField()),
                ("small", models.BinaryField()),
                ("is_approved", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_club_logos",
                        to="users.agent",
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logos",
                        to="clubs.club",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_approved", True)),
                        fields=("club",),
                        name="one_approved_logo_per_club",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_approved", False)),
                        fields=("club",),
                        name="one_pending_logo_per_club",
                    ),
                ],
            },
        ),
    ]
