# Generated by Django 5.2.6 on 2025-10-16 19:59

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clubs", "0015_alter_club_email"),
        ("competitions", "0013_rename_type_to_environment"),
    ]

    operations = [
        migrations.CreateModel(
            name="InternationalTournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=48)),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                ("city", models.CharField(max_length=48)),
                ("country", django_countries.fields.CountryField(max_length=2)),
                (
                    "type",
                    models.IntegerField(
                        choices=[(1, "National Team"), (2, "European League"), (3, "Others")]
                    ),
                ),
                (
                    "environment",
                    models.IntegerField(choices=[(1, "Outdoor"), (2, "Indoor"), (3, "Beach")]),
                ),
                (
                    "fee_type",
                    models.IntegerField(choices=[(1, "Free"), (2, "Discounted"), (3, "Regular")]),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="international_tournaments",
                        to="competitions.season",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamAtInternationalTournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team_name",
                    models.CharField(
                        help_text=(
                            "Team name at the time of participation (for historical purposes)"
                        ),
                        max_length=48,
                    ),
                ),
                (
                    "age_limit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="competitions.agelimit",
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="competitions.division"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="international_tournament_participations",
                        to="clubs.team",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="team_participations",
                        to="international_tournaments.internationaltournament",
                    ),
                ),
            ],
            options={
                "unique_together": {("tournament", "team", "age_limit", "division")},
            },
        ),
        migrations.AddField(
            model_name="internationaltournament",
            name="teams",
            field=models.ManyToManyField(
                related_name="international_tournaments",
                through="international_tournaments.TeamAtInternationalTournament",
                to="clubs.team",
            ),
        ),
    ]
