# Generated by Django 5.2.6 on 2025-10-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("international_tournaments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamatinternationaltournament",
            name="final_placement",
            field=models.IntegerField(
                blank=True, help_text="Final placement at the tournament", null=True
            ),
        ),
        migrations.AddField(
            model_name="teamatinternationaltournament",
            name="total_teams",
            field=models.IntegerField(
                blank=True,
                help_text="Total number of teams at the tournament in this division",
                null=True,
            ),
        ),
    ]
