# Generated by Django 5.2.6 on 2025-11-03 14:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "international_tournaments",
            "0002_teamatinternationaltournament_final_placement_and_more",
        ),
        ("members", "0010_alter_member_email_alter_member_legal_guardian_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberAtInternationalTournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_captain",
                    models.BooleanField(
                        default=False,
                        help_text="Only one captain per team is allowed",
                        verbose_name="Captain",
                    ),
                ),
                (
                    "is_spirit_captain",
                    models.BooleanField(
                        default=False,
                        help_text="Only one spirit captain per team is allowed",
                        verbose_name="Spirit captain",
                    ),
                ),
                ("is_coach", models.BooleanField(default=False, verbose_name="Coach")),
                (
                    "jersey_number",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(99),
                        ],
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="members.member"
                    ),
                ),
                (
                    "team_at_tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="members",
                        to="international_tournaments.teamatinternationaltournament",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="members",
                        to="international_tournaments.internationaltournament",
                    ),
                ),
            ],
            options={
                "unique_together": {("team_at_tournament", "member"), ("tournament", "member")},
            },
        ),
    ]
